language: rust
rust: nightly

addons:
  firefox: latest
  chrome: stable

install:
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

script:
  - cd public
  - cargo test
  - wasm-pack test --firefox --headless
  - wasm-pack test --chrome  --headless
  - cd ../core
  - cargo test
  - cd ../server
  - cargo test
