name: docker
on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build Docker
        run: |
          docker build .
