name: test
on: [ push, pull_request ]

jobs:
  ci:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        build: [ stable, beta, nightly, macos ]

        include:
          - build: stable
            os: ubuntu-latest
            rust: stable

          - build: beta
            os: ubuntu-latest
            rust: beta

          - build: nightly
            os: ubuntu-latest
            rust: nightly

          - build: macos
            os: macos-latest
            rust: stable

    steps:
      - uses: actions/checkout@v2

      - name: Setting up rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Checking if it builds without errors
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path config/Cargo.toml

      - name: Checking if it builds without errors
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path mighty/Cargo.toml --features server

      - name: Checking if it builds without errors
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path mighty/Cargo.toml --features client

      - name: Checking if it builds without errors
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path public/Cargo.toml

      - name: Checking if it builds without errors
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path server/Cargo.toml

      - name: Checking if it builds without errors
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path server/Cargo.toml --features watch-file

      - name: Checking if it builds without errors
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path types/Cargo.toml

      - name: Checking if it builds without errors
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path types/Cargo.toml --features server

      - name: Testing wasm
        run: |
          if [ -f "${HOME}/.cargo/bin/wasm-pack" ]; then
            rm ${HOME}/.cargo/bin/wasm-pack
          fi
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          cd public && wasm-pack test ${{ matrix.browsers }} --headless
